"""updated schema

Revision ID: 5db28fa97e06
Revises: ddacd663e2e2
Create Date: 2023-09-07 10:50:05.853138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5db28fa97e06'
down_revision: Union[str, None] = 'ddacd663e2e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('museum_artists', schema=None) as batch_op:
        batch_op.alter_column('museum_id',
               existing_type=sa.INTEGER(),
               nullable=True, unique = False)
        batch_op.alter_column('artists_id',
               existing_type=sa.INTEGER(),
               nullable=True, unique = False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('museum_artists', schema=None) as batch_op:
        batch_op.alter_column('artists_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('museum_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
