"""updated relationships

Revision ID: 8b42fdcbad6f
Revises: ea3b45ea8286
Create Date: 2023-09-07 10:27:31.204884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b42fdcbad6f'
down_revision: Union[str, None] = 'ea3b45ea8286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
