"""updated relationships

Revision ID: ea3b45ea8286
Revises: 3f61c3a017b8
Create Date: 2023-09-07 10:20:30.406384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea3b45ea8286'
down_revision: Union[str, None] = '3f61c3a017b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('museum_artists')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('museum_artists',
    sa.Column('museum_id', sa.INTEGER(), nullable=False),
    sa.Column('artists_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['artists_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['museum_id'], ['museums.id'], ),
    sa.PrimaryKeyConstraint('museum_id', 'artists_id')
    )
    # ### end Alembic commands ###
